import type { Metadata } from "next";

import "./globals.css";
import Navbar from "@/components/Navbar";
import {Poppins} from "next/font/google"
import { auth } from "@/auth";


const poppins = Poppins ({
  subsets:["latin"],
  weight:["300","400","500","700","900"]

})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body
        className={`${poppins.className}antialiased`}
      >
        <Navbar user={session?.user!} />
        {children}
      </body>
    </html>
  );
}
